### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by suji2901**

### CODE REVIEW

**Comment by suji2901** [comment]
First Commit comment

**Review by cormullion — COMMENTED** [review]
Why are you making this PR?

**Comment by suji2901** [comment]
Just as an example for explaining GIT concepts..

**Comment by cormullion** [comment]
is this something to do with Hacktoberfest?

**Comment by suji2901** [comment]
No..just a demo for students on GIT concepts

**Comment by cormullion** [comment]
Well, you’re setting a bad example by making a poor quality PR that’s not even constructive. PRs should make improvements, not add meaningless headings.

**Pull request closed without merging**
